font_family      Hack Nerd Font Mono
bold_font        Hack Nerd Font Mono Bold
italic_font      Hack Nerd Font Mono Italic
bold_italic_font Hack Nerd Font Mono Bold Italic

shell_intergration no-cursor
shell zsh
cursor #e04671
cursor_shape block
cursor_text_color #4698e0
selection_background #e099d8

font_size        12
background_opacity 0.85
dynamic_background_opacity yes
