splash = false

wallpaper {
    monitor = eDP-1
    path = ~/.config/hypr/wallpaper/master/
    timeout = 300
    order = random
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hypr/wallpaper/slave/
    timeout = 200
    order = random
}

wallpaper {
    monitor = *
    path = ~/.config/hypr/wallpaper/master/
    timeout = 300
    order = random
}
